### PR TITLE
Remove replacement rule for participle in go.mod

### PR DESCRIPTION
**Pull request by mewmew**
Also, fix a tiny typo in the README.

### CODE REVIEW

**Comment by mewmew** [comment]
Hi @alecthomas,

Really cool start on an experimental language! I've been missing sumtypes in Go for some time. It's possible to work around, but the workarounds are not always pretty.

Happy to see that you are experimenting with these kind of ideas! I'll be following with excitement :)

Wish you a lovely start of the new years and good adventures to come!

Cheerful regards,
Robin

**Comment by alecthomas** [comment]
Thanks!

**Comment by alecthomas** [comment]
Yes! I do miss sum types, immutability, and a few other things, when using Go. It's fun playing around with some ideas. I'm not sure about the immutability model, I think I'll need to play with it to see if it's usable.

**Comment by alecthomas** [comment]
Happy New Year to you too :)

**Pull request merged**
